"""A thin etcd v3 client over the gRPC-gateway's JSON API.

Why this exists rather than a dependency:

- **`etcd3` cannot be imported beside a modern protobuf.** It vendors stubs
  generated by protoc < 3.19 and raises `TypeError: Descriptors cannot be
  created directly` under protobuf 4+/5+. Any application that already pins
  protobuf — anything using pymilvus, or most gRPC clients — cannot install it.
- **`etcd3gw` works, but discards the one field this design is built on.** Its
  `get_prefix` returns values and per-key metadata and drops the response
  header, so there is no way to learn the revision a read happened at. Without
  that number there is no consistent snapshot, no watch that resumes where a
  read left off, and no pinned resolution. See ARCHITECTURE.md.

So the surface below is only what the layout above it needs — range, put,
delete, txn, watch, compact, status — and every revision the server reports is
carried out rather than swallowed.

Everything the gateway takes or returns as a key or value is base64; everything
it reports as a 64-bit integer is a JSON *string* (`"revision": "7"`), which is
why `_int` appears on every read. Both are gateway quirks, not etcd's.
"""

from __future__ import annotations

import base64
import json
from collections.abc import Iterator, Mapping, Sequence
from dataclasses import dataclass
from typing import Any, Literal

import requests

# etcd refuses a request whose payload exceeds --max-request-bytes (1.5 MiB by
# default) and the whole store is capped by --quota-backend-bytes (2 GiB by
# default), beyond which the cluster wedges into a read-only NOSPACE alarm. A
# config store should never come close, so it fails loudly here instead: a
# 64 KiB value means someone is checking in a payload that belongs in object
# storage, and finding that out on write is much better than finding it out
# when the cluster stops accepting writes.
MAX_VALUE_BYTES = 64 * 1024


class EtcdError(RuntimeError):
    """A request etcd refused, carrying the gateway's own message."""


class EtcdUnavailable(EtcdError):
    """etcd could not be reached at all — the case a client must survive."""


@dataclass(frozen=True, slots=True)
class KeyValue:
    """One key as etcd holds it, with the MVCC metadata that makes it versioned.

    `mod_revision` is the useful one: it is the revision that last wrote this
    key, so it doubles as an entity tag for compare-and-swap. `version` is a
    per-key counter (1 on create) and is reset by a delete; `create_revision`
    survives nothing but the key's own lifetime. Prefer `mod_revision` for
    optimistic concurrency and ignore the other two unless you mean them.
    """

    key: str
    value: bytes
    create_revision: int
    mod_revision: int
    version: int

    def json(self) -> Any:
        """The value decoded as JSON — how this store encodes every value."""
        return json.loads(self.value.decode("utf-8"))


@dataclass(frozen=True, slots=True)
class RangeResult:
    """The keys a range read returned, and the revision it read at.

    The revision is the point of the type. A range over a prefix is atomic in
    etcd — every key comes from one MVCC snapshot — so this number names that
    snapshot exactly, and a watch started at `revision + 1` is guaranteed to
    report every change that happened after it and none that happened before.
    That is the seam a poll-based store cannot close.
    """

    revision: int
    kvs: tuple[KeyValue, ...]

    def as_dict(self) -> dict[str, KeyValue]:
        return {kv.key: kv for kv in self.kvs}


EventType = Literal["PUT", "DELETE"]


@dataclass(frozen=True, slots=True)
class Event:
    type: EventType
    kv: KeyValue


@dataclass(frozen=True, slots=True)
class WatchBatch:
    """One message from a watch stream.

    Four shapes arrive on this channel and callers must tell them apart:

    - **a creation acknowledgement** (`created`) — the first message on every
      stream, carrying no events and the revision the *store* is at, which is
      emphatically not the revision the watch has delivered up to. Advancing a
      resume cursor on it skips every change between the requested start and
      now: the events are still coming, but a connection that breaks before
      they arrive leaves a client resuming past changes it never saw, stale
      forever with no error anywhere. Distinguishable only by this flag — a
      progress notification looks otherwise identical.
    - **events** — the ordinary case, one or more changes that happened
      together. Changes made in a single etcd transaction arrive in a single
      batch, which is what lets a client apply a multi-key config change without
      ever observing half of it.
    - **a progress notification** — no events, no `created`, a newer revision.
      Requested with
      `progress_notify`; it keeps an idle stream alive through NAT timeouts and
      moves the resume cursor forward so a reconnect after a quiet hour does not
      ask for an hour-old revision.
    - **a cancellation with `compact_revision` set** — the revision the client
      asked to resume from has been compacted away, so the history between then
      and now no longer exists. There is no way to catch up incrementally: the
      only correct response is to re-read the whole prefix. Treating this as a
      transient error is the classic etcd watch bug, and it presents as config
      that is silently stale forever.
    """

    revision: int
    events: tuple[Event, ...]
    created: bool = False
    compact_revision: int = 0
    canceled: bool = False
    cancel_reason: str = ""

    @property
    def lost_history(self) -> bool:
        """Whether the resume point is gone and a full re-read is required."""
        return self.compact_revision > 0


def _b64(raw: str | bytes) -> str:
    if isinstance(raw, str):
        raw = raw.encode("utf-8")
    return base64.b64encode(raw).decode("ascii")


def _unb64(encoded: str | None) -> bytes:
    return base64.b64decode(encoded) if encoded else b""


def _int(raw: Any) -> int:
    """Coerce the gateway's stringified 64-bit integers, absent meaning zero."""
    return int(raw) if raw is not None else 0


def prefix_end(prefix: str) -> bytes:
    """The exclusive upper bound that makes a range read cover a prefix.

    etcd has no prefix operator: `range_end` is "one past the last key I want",
    so a prefix scan is the prefix with its final byte incremented.

    The final branch is defensive rather than reachable: a prefix whose every
    byte is 0xff has no successor and means "to the end of the keyspace", which
    etcd spells as a single NUL byte — but UTF-8 never encodes a trailing 0xff,
    so no `str` can get there. It stays because the alternative is a function
    that is only correct for the inputs `layout` happens to validate.
    """
    raw = bytearray(prefix.encode("utf-8"))
    for i in range(len(raw) - 1, -1, -1):
        if raw[i] < 0xFF:
            raw[i] += 1
            return bytes(raw[: i + 1])
    return b"\0"


def _kv(raw: Mapping[str, Any]) -> KeyValue:
    return KeyValue(
        key=_unb64(raw.get("key")).decode("utf-8"),
        value=_unb64(raw.get("value")),
        create_revision=_int(raw.get("create_revision")),
        mod_revision=_int(raw.get("mod_revision")),
        version=_int(raw.get("version")),
    )


class Etcd:
    """A connection to one etcd endpoint.

    Not a cluster-aware client: it speaks to the address it is given, and if
    that member is down it raises `EtcdUnavailable` rather than failing over.
    That is the honest boundary for a gateway client, and it is enough here
    because the read path never depends on etcd being reachable — see
    `client.ConfigClient`, which serves from a local snapshot and treats an
    unreachable store as a staleness problem rather than an outage.
    """

    def __init__(
        self,
        url: str = "http://127.0.0.1:2379",
        *,
        timeout: float = 5.0,
        user: str | None = None,
        password: str | None = None,
        session: requests.Session | None = None,
    ) -> None:
        self._url = url.rstrip("/")
        self._timeout = timeout
        self._session = session or requests.Session()
        if user is not None and password is not None:
            self._authenticate(user, password)

    # -- plumbing ---------------------------------------------------------

    def _authenticate(self, user: str, password: str) -> None:
        token = self._post(
            "/v3/auth/authenticate", {"name": user, "password": password}
        )
        self._session.headers["Authorization"] = str(token["token"])

    def _post(
        self, path: str, body: Mapping[str, Any], *, timeout: float | None = -1.0
    ) -> dict[str, Any]:
        try:
            response = self._session.post(
                f"{self._url}{path}",
                json=body,
                timeout=self._timeout if timeout == -1.0 else timeout,
            )
        except requests.RequestException as exc:
            raise EtcdUnavailable(f"etcd at {self._url} is unreachable: {exc}") from exc
        if response.status_code >= 400:
            raise EtcdError(
                f"etcd refused {path} with {response.status_code}: "
                f"{response.text[:500]}"
            )
        parsed: dict[str, Any] = response.json()
        return parsed

    def clone(self) -> Etcd:
        """A second connection to the same endpoint, with its own socket pool.

        The watch loop holds one of these. A watch occupies its connection for
        as long as it lives, so sharing a session with ordinary reads would
        either block them behind the stream or make `stop()` — which closes the
        session to unblock a thread parked on a socket read — tear down reads
        that have nothing to do with it.
        """
        twin = Etcd(self._url, timeout=self._timeout)
        twin._session.headers.update(self._session.headers)
        return twin

    def close(self) -> None:
        """Close the underlying sockets, unblocking any watch parked on one."""
        self._session.close()

    # -- reads ------------------------------------------------------------

    def range(
        self,
        key: str,
        *,
        prefix: bool = False,
        revision: int = 0,
        limit: int = 0,
        keys_only: bool = False,
        sort_order: Literal["NONE", "ASCEND", "DESCEND"] = "NONE",
        sort_target: Literal["KEY", "MOD", "CREATE", "VERSION", "VALUE"] = "KEY",
    ) -> RangeResult:
        """Read one key, or every key under it when `prefix` is set.

        `revision` reads the keyspace as it stood at that revision — etcd's
        native point-in-time read, and what makes pinned resolution a property
        of the store rather than a column someone has to maintain. It is bounded
        by compaction: a revision older than the compaction point is gone, and
        etcd answers with an error rather than with approximate data.
        """
        body: dict[str, Any] = {"key": _b64(key)}
        if prefix:
            body["range_end"] = _b64(prefix_end(key))
        if revision:
            body["revision"] = str(revision)
        if limit:
            body["limit"] = str(limit)
        if keys_only:
            body["keys_only"] = True
        if sort_order != "NONE":
            # Spelled out rather than left to the server's default, which is
            # documented as unordered: a history listing that is *usually* in
            # order is the kind of thing that breaks once, in production.
            body["sort_order"] = sort_order
            body["sort_target"] = sort_target
        raw = self._post("/v3/kv/range", body)
        return RangeResult(
            revision=_int(raw.get("header", {}).get("revision")),
            kvs=tuple(_kv(kv) for kv in raw.get("kvs", ())),
        )

    def status(self) -> dict[str, Any]:
        """Cluster health, including `dbSize` and the current `raftTerm`."""
        return self._post("/v3/maintenance/status", {})

    # -- writes -----------------------------------------------------------

    def put(self, key: str, value: bytes, *, lease: int = 0) -> int:
        """Write one key; returns the revision the write landed at."""
        if len(value) > MAX_VALUE_BYTES:
            raise EtcdError(
                f"value for {key} is {len(value)} bytes, over the "
                f"{MAX_VALUE_BYTES}-byte ceiling this store enforces"
            )
        body: dict[str, Any] = {"key": _b64(key), "value": _b64(value)}
        if lease:
            body["lease"] = str(lease)
        raw = self._post("/v3/kv/put", body)
        return _int(raw.get("header", {}).get("revision"))

    def delete(self, key: str, *, prefix: bool = False) -> int:
        body: dict[str, Any] = {"key": _b64(key)}
        if prefix:
            body["range_end"] = _b64(prefix_end(key))
        raw = self._post("/v3/kv/deleterange", body)
        return _int(raw.get("header", {}).get("revision"))

    def txn(
        self,
        *,
        compare: Sequence[Mapping[str, Any]] = (),
        success: Sequence[Mapping[str, Any]] = (),
        failure: Sequence[Mapping[str, Any]] = (),
    ) -> tuple[bool, int, dict[str, Any]]:
        """Run a transaction; returns (succeeded, revision, raw response).

        This is the primitive that replaces `BEGIN … COMMIT`. Every comparison
        is evaluated and every operation applied at one revision, so a config
        change spanning several keys is one atomic event to every watcher —
        which is the property that makes `admin.apply` safe to expose to a UI.
        """
        raw = self._post(
            "/v3/kv/txn",
            {
                "compare": list(compare),
                "success": list(success),
                "failure": list(failure),
            },
        )
        return (
            bool(raw.get("succeeded", False)),
            _int(raw.get("header", {}).get("revision")),
            raw,
        )

    def compact(self, revision: int, *, physical: bool = False) -> None:
        """Discard MVCC history before `revision`.

        Required, not optional: without compaction the backend grows until it
        trips the quota alarm and the cluster stops accepting writes. It is also
        destructive in a way that matters to this design — it is what makes
        etcd revisions unusable as an audit log, and why history is written to
        keys of its own. See `admin.ConfigAdmin.set`.
        """
        self._post(
            "/v3/kv/compaction", {"revision": str(revision), "physical": physical}
        )

    # -- watch ------------------------------------------------------------

    def watch(
        self,
        key: str,
        *,
        prefix: bool = True,
        start_revision: int = 0,
        progress_notify: bool = True,
        read_timeout: float | None = None,
    ) -> Iterator[WatchBatch]:
        """Stream changes under `key`, resuming from `start_revision`.

        The gateway answers with newline-delimited JSON on a connection it holds
        open, so this is a generator that yields for as long as the caller keeps
        consuming it and raises `EtcdUnavailable` when the stream breaks. Read
        timeout defaults to none because an idle watch is *supposed* to be
        silent; `progress_notify` is what proves the connection is still alive.
        """
        create: dict[str, Any] = {"key": _b64(key)}
        if prefix:
            create["range_end"] = _b64(prefix_end(key))
        if start_revision:
            create["start_revision"] = str(start_revision)
        if progress_notify:
            create["progress_notify"] = True
        try:
            response = self._session.post(
                f"{self._url}/v3/watch",
                json={"create_request": create},
                stream=True,
                timeout=(self._timeout, read_timeout),
            )
        except requests.RequestException as exc:
            raise EtcdUnavailable(
                f"watch on {self._url} failed to open: {exc}"
            ) from exc
        if response.status_code >= 400:
            raise EtcdError(
                f"watch refused with {response.status_code}: {response.text[:500]}"
            )
        try:
            for line in response.iter_lines():
                if not line:
                    continue
                message = json.loads(line)
                if "error" in message:
                    raise EtcdError(f"watch stream error: {message['error']}")
                result = message.get("result", {})
                yield WatchBatch(
                    revision=_int(result.get("header", {}).get("revision")),
                    events=tuple(
                        Event(type=e.get("type", "PUT"), kv=_kv(e.get("kv", {})))
                        for e in result.get("events", ())
                    ),
                    created=bool(result.get("created", False)),
                    compact_revision=_int(result.get("compact_revision")),
                    canceled=bool(result.get("canceled", False)),
                    cancel_reason=str(result.get("cancel_reason", "")),
                )
        except requests.RequestException as exc:
            raise EtcdUnavailable(f"watch stream on {self._url} broke: {exc}") from exc
        finally:
            response.close()
